---
- name: "Reset Kubernetes"
  shell: echo $(kubeadm reset -f && echo 'true') 

- name: "Remove docker images" 
  shell: echo $(docker rmi --force $(docker images --all -q) && echo 'true')
  become: true

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: "apt-get purge packages"
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl', 'docker-ce']
    state: absent
    purge: yes
    autoremove: yes
    force: yes

- name: "Remove pod logging"
  file:
    path: "{{ item }}"
    state: absent
  become: True
  loop:
    - /var/log/pods

  # some extra cleanup https://stackoverflow.com/a/41372829/571593
- name: "Remove .kube folder"
  shell: rm -rf /root/.kube 
  become: True

- name: "Remove /etc/kubernetes"
  shell: rm -rf /etc/kubernetes
  become: True

- name: "Remove etcd persistence"
  shell: rm -rf /var/lib/etcd
  become: True

- name: "Remove kubelet leftovers"
  shell: rm -rf /var/lib/kubelet
  become: True

- name: "Remove CNI leftovers"
  shell: rm -rf /var/lib/cni && rm -rf /etc/cni
  become: True

- name: "Remove Flannel leftovers"
  shell: rm -rf /run/flannel
  become: True

- name: Reboot
  reboot:
    reboot_timeout: 120
